# Generated by Django 2.2.3 on 2019-07-05 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0002_auto_20190705_0802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='Office',
            name='company',
        ),
        migrations.AddField(
            model_name='Office',
            name='company',
            field=models.ManyToManyField(to='offices.Company'),
        ),
    ]
