# Generated by Django 2.2.3 on 2019-07-05 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0003_auto_20190705_0806'),
    ]

    operations = [
        migrations.RenameField(
            model_name='Office',
            old_name='company',
            new_name='companies',
        ),
    ]
