# Generated by Django 2.2.3 on 2019-07-05 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0004_auto_20190705_0811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='Office',
            name='companies',
        ),
        migrations.AddField(
            model_name='Office',
            name='company',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='offices', to='offices.Company'),
        ),
        migrations.AddField(
            model_name='Office',
            name='headquarter',
            field=models.OneToOneField(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='offices.Company'),
        ),
        migrations.DeleteModel(
            name='CompanyHeadquarter',
        ),
    ]
