# Generated by Django 2.2.3 on 2019-07-05 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0009_auto_20190705_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='Office',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, parent_link=True, related_name='offices', to='offices.Company'),
        ),
    ]
