# Generated by Django 2.2.3 on 2019-07-05 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0010_auto_20190705_0912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='Office',
            name='company',
        ),
        migrations.AddField(
            model_name='company',
            name='offices',
            field=models.ManyToManyField(related_name='company', to='offices.Office'),
        ),
    ]
