# Generated by Django 2.2.3 on 2019-07-05 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0011_auto_20190705_0942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='Office',
            name='headquarter',
        ),
        migrations.RemoveField(
            model_name='Office',
            name='monthly_rent',
        ),
        migrations.RemoveField(
            model_name='company',
            name='offices',
        ),
        migrations.CreateModel(
            name='CompanyOffice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headquarter', models.BooleanField(default=False)),
                ('monthly_rent', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company', to='offices.Office')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='offices',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Office', to='offices.CompanyOffice'),
        ),
    ]
