# Generated by Django 2.2.3 on 2019-07-05 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0012_auto_20190705_1012'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyoffice',
            old_name='house',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='company',
            name='offices',
        ),
        migrations.RemoveField(
            model_name='companyoffice',
            name='headquarter',
        ),
        migrations.AddField(
            model_name='companyoffice',
            name='company',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='offices', to='offices.Company'),
        ),
        migrations.AddField(
            model_name='companyoffice',
            name='uniq_place',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='Office',
            name='building',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Building'),
        ),
        migrations.AddField(
            model_name='Office',
            name='country',
            field=models.CharField(blank=True, max_length=256, verbose_name='Country'),
        ),
        migrations.CreateModel(
            name='CompanyHeadquarter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniq_place', models.CharField(blank=True, max_length=128, null=True)),
                ('monthly_rent', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='headquarter_for', to='offices.Office')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='headquarter',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='company', to='offices.CompanyHeadquarter'),
        ),
    ]
