# Generated by Django 2.2.3 on 2019-07-05 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0013_auto_20190705_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='headquarter',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='company', to='offices.CompanyHeadquarter'),
        ),
    ]
