# Generated by Django 2.2.3 on 2019-07-05 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0014_auto_20190705_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyheadquarter',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='headquarter_for', to='offices.Office', unique=True),
        ),
        migrations.AlterField(
            model_name='companyoffice',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company', to='offices.Office', unique=True),
        ),
    ]
