# Generated by Django 2.2.3 on 2019-07-05 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0016_auto_20190705_1102'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyheadquarter',
            options={'verbose_name_plural': 'companies headquarter'},
        ),
        migrations.AlterField(
            model_name='companyheadquarter',
            name='uniq_place',
            field=models.CharField(blank=True, default='', max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='companyoffice',
            name='uniq_place',
            field=models.CharField(blank=True, default='', max_length=128, unique=True),
        ),
    ]
