# Generated by Django 2.2.3 on 2019-07-05 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0017_auto_20190705_1125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyheadquarter',
            old_name='uniq_place',
            new_name='concrete_location',
        ),
        migrations.RenameField(
            model_name='companyoffice',
            old_name='uniq_place',
            new_name='concrete_location',
        ),
    ]
