# Generated by Django 2.2.3 on 2019-07-05 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0018_auto_20190705_1133'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='companyoffice',
            unique_together={('concrete_location', 'location')},
        ),
    ]
