# Generated by Django 2.2.3 on 2019-07-05 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0019_auto_20190705_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyheadquarter',
            name='concrete_location',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='companyoffice',
            name='concrete_location',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterUniqueTogether(
            name='companyheadquarter',
            unique_together={('concrete_location', 'location')},
        ),
    ]
