# Generated by Django 2.2.3 on 2019-07-06 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0020_auto_20190705_1205'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='companyoffice',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='companyoffice',
            name='company',
        ),
        migrations.RemoveField(
            model_name='companyoffice',
            name='location',
        ),
        migrations.RemoveField(
            model_name='Office',
            name='building',
        ),
        migrations.AddField(
            model_name='Office',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offices', to='offices.Company'),
        ),
        migrations.AlterField(
            model_name='company',
            name='headquarter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='isHeadquarter', to='offices.Office'),
        ),
        migrations.DeleteModel(
            name='CompanyHeadquarter',
        ),
        migrations.DeleteModel(
            name='CompanyOffice',
        ),
    ]
