# Generated by Django 2.2.3 on 2019-07-06 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0021_auto_20190706_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='headquarter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='isHeadquarter', to='offices.Office', unique=True),
        ),
    ]
