# Generated by Django 2.2.3 on 2019-07-06 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0023_auto_20190706_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='headquarter',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='isHeadquarter', to='offices.Office'),
        ),
    ]
