# Generated by Django 2.2.3 on 2019-07-06 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0024_auto_20190706_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='Office',
            name='monthly_rent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
